runtime: python27

handlers:
- url: /static
  static_dir: static
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  
- url: /.*
  script: index.php
