runtime: php55

handlers:
- url: /static
  static_dir: static
  
- url: /static/(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
  
- url: /.*
  script: index.html
